# Dependencies
highlighter: none
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

title: "Mirador"
tagline: "Development progress and project notes"
description: "Development Log"
author:
  name: "Aidan Wagner"
  url: "https://finitesample.space"

github:
  repo: https://github.com/DetectiveFierce/mirador

plugins:
  - jekyll-gist
  - jekyll-redirect-from

sidebar_pages:
  - /about/
  - /app/
  - /game/
  - /maze/
  - /renderer/
  - /ui/
