# Dependencies
markdown: kramdown
highlighter: rouge

title: "Blog"
tagline: "Development progress and project notes"
description: "A minimal blog to track my project development."
author:
  name: "Aidan Wagner"
  url: "https://finitesample.space"

github:
  repo: https://github.com/JesusButForGayPeople/finitesample.space
