# Dependencies
markdown: kramdown
highlighter: rouge

title: "Mirador"
tagline: "Development progress and project notes"
description: "Development Log"
author:
  name: "Aidan Wagner"
  url: "https://finitesample.space"

github:
  repo: https://github.com/JesusButForGayPeople/finitesample.space

plugins:
  - jekyll-gist
